---
- name: Confirm Rhel Version Supported
  assert:
    that: ansible_distribution_major_version in redhat_supported_versions
    fail_msg: >-
      Rhel Version: {{ansible_distribution_major_version}} not in supported versions: {{redhat_supported_versions}}.
      To skip host validations, set validate_hosts to false.
  vars:
    redhat_supported_versions: ['7', '8']
  when: ansible_os_family == "RedHat"
  tags: validate

- name: Confirm Ubuntu Version Supported
  assert:
    that: ansible_distribution_major_version in ubuntu_supported_versions
    fail_msg: >-
      Ubuntu Version: {{ansible_distribution_major_version}} not in supported versions: {{ubuntu_supported_versions}}.
      To skip host validations, set validate_hosts to false.
  vars:
    ubuntu_supported_versions: ['16', '18']
  when: ansible_distribution == "Ubuntu"
  tags: validate

- name: Confirm Debian Version Supported
  assert:
    that: ansible_distribution_major_version in debian_supported_versions
    fail_msg: >-
      Debian Version: {{ansible_distribution_major_version}} not in supported versions: {{debian_supported_versions}}.
      To skip host validations, set validate_hosts to false.
  vars:
    debian_supported_versions: ['9']
  when: ansible_distribution == "Debian"
  tags: validate

- name: Check Internet Access for Confluent Packages/Archive
  uri:
    url: "{{confluent_common_repository_baseurl}}"
    status_code: 200
  when: >
    ( installation_method == 'package' and repository_configuration == 'confluent') or
    ( installation_method == 'archive' and confluent_common_repository_baseurl in confluent_archive_file_source )
  ignore_errors: true
  register: internet_access_check
  tags: validate

- name: Fail Provisioning because No Network Connectivity
  fail:
    msg: >-
      Failed to connect to Package Repository at {{confluent_common_repository_baseurl}} from Host.
      Confirm network connectivity. To skip host validations, set validate_hosts to false.
  when: internet_access_check.failed | default(False)
